{{- if .Values.prometheus.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-agent.serviceAccountName" . }}
  namespace: {{ template "prometheus-agent.namespace" . }}
  labels:
    app: {{ template "prometheus-agent.name" . }}
    app.kubernetes.io/name: {{ template "prometheus-agent.name" . }}
    app.kubernetes.io/component: prometheus
{{- end }}