# This file is used to configure the OpenTelemetry Collector for collecting 
# logs from the host and sending them to Coralogix.
# The file is intended to be used an example and should be modified to fit your needs.

# All values prefixed with $ are environment variables that are set by the ECS task definition and
# swapped out at runtime. These values can be hard-coded if you are not using ECS or if you are
# using your own configuration with the ECS wrapper.

receivers:
  filelog:
    start_at: beginning

    # note that the host filesystem is mounted at /hostfs
    include:
      - /hostfs/var/log/*.log
      - /hostfs/var/log/messages
      - /hostfs/var/log/dmesg
      - /hostfs/var/log/xm/*.log
      - /hostfs/var/lib/docker/containers/*/*.log
    include_file_path: true

    operators:
      - type: move
        from: attributes["log.file.name"]
        to: resource["log.file.name"]

processors:
  resourcedetection/ecs:
    detectors: [env, ecs]
    timeout: 2s
    override: false

exporters:
  logging:
  coralogix:
    logs:
      endpoint: "$LOGS_ENDPOINT"
    private_key: "$PRIVATE_KEY"
    application_name: "OTel"
    subsystem_name: "ECS"
    application_name_attributes:
    - "APP_NAME"
    - "service.namespace"
    subsystem_name_attributes:
    - "SUB_SYS"
    - "aws.ecs.task.family"
    - "service.name"
    timeout: 30s

service:
  pipelines:
    logs:
      receivers: 
        - filelog
      processors:
        - resourcedetection/ecs
      exporters:
        - logging
        - coralogix