---
# Source: fluent-bit-http/charts/fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-http
  labels:
    helm.sh/chart: fluent-bit-0.19.20
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit-http
    app.kubernetes.io/version: "1.8.13"
    app.kubernetes.io/managed-by: Helm
---
# Source: fluent-bit-http/charts/fluent-bit/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-http
  labels:
    helm.sh/chart: fluent-bit-0.19.20
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit-http
    app.kubernetes.io/version: "1.8.13"
    app.kubernetes.io/managed-by: Helm
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        storage.metrics on
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Refresh_Interval 5
        Skip_Long_Lines On
        Mem_Buf_Limit 25MB
        DB /var/log/fluentbit-tail.db
    
    @INCLUDE input-systemd.conf
    [FILTER]
        Name kubernetes
        Match kube.*
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Use_Kubelet On
        Annotations Off
        Labels On
        Buffer_Size 0
        Keep_Log Off
        Merge_Log_Key log_obj
        Merge_Log On
    
    [FILTER]
        Name            nest
        Match           kube.*
        Operation       lift
        Nested_under    kubernetes
        Add_prefix      kubernetes.
    
    [FILTER]
        Name    modify
        Match   kube.*
        Copy    ${APP_NAME} applicationName
        Copy    ${SUB_SYSTEM} subsystemName 
    
    [FILTER]
        Name            nest
        Match           kube.*
        Operation       nest
        Wildcard        kubernetes.*
        Nest_under      kubernetes
        Remove_prefix   kubernetes.
    
    [FILTER]
        Name        nest
        Match       kube.*
        Operation   nest
        Wildcard    kubernetes
        Wildcard    log
        Wildcard    log_obj
        Wildcard    stream
        Wildcard    time 
        Nest_under  json 
    
    @INCLUDE filters-systemd.conf
    [OUTPUT]
        Name                  http
        Match                 kube.*
        Host                  ${ENDPOINT}
        Port                  443
        URI                   /logs/rest/singles
        Format                json_lines
        TLS                   On
        Header                private_key ${PRIVATE_KEY}
        compress              gzip
        Retry_Limit           10
    
    @INCLUDE output-systemd.conf
  filters-systemd.conf: |
    [FILTER]
      Name    modify
      Match   host.*
      Add    applicationName ${APP_NAME_SYSTEMD} 
      Add    subsystemName ${SUB_SYSTEM_SYSTEMD} 
    
    [FILTER]
      Name        nest
      Match       host.*
      Operation   nest
      Wildcard    _HOSTNAME
      Wildcard    SYSLOG_IDENTIFIER
      Wildcard    _CMDLINE 
      Wildcard    MESSAGE
      Nest_under  json 
  input-systemd.conf: |
    [INPUT]
      Name systemd
      Tag host.*
      Systemd_Filter _SYSTEMD_UNIT=kubelet.service
      Read_From_Tail On 
      Mem_Buf_Limit 5MB  
  output-systemd.conf: |
    [OUTPUT]
      Name                  http
      Match                 host.*
      Host                  ${ENDPOINT}
      Port                  443
      URI                   /logs/rest/singles
      Format                json_lines
      TLS                   On
      Header                private_key ${PRIVATE_KEY}
      compress              gzip
      Retry_Limit           10
---
# Source: fluent-bit-http/charts/fluent-bit/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-http
  labels:
    helm.sh/chart: fluent-bit-0.19.20
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit-http
    app.kubernetes.io/version: "1.8.13"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
---
# Source: fluent-bit-http/charts/fluent-bit/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-http
  labels:
    helm.sh/chart: fluent-bit-0.19.20
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit-http
    app.kubernetes.io/version: "1.8.13"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-http
subjects:
  - kind: ServiceAccount
    name: fluent-bit-http
    namespace: default
---
# Source: fluent-bit-http/charts/fluent-bit/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-http
  labels:
    helm.sh/chart: fluent-bit-0.19.20
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit-http
    app.kubernetes.io/version: "1.8.13"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 2020
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit-http
---
# Source: fluent-bit-http/charts/fluent-bit/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-http
  labels:
    helm.sh/chart: fluent-bit-0.19.20
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit-http
    app.kubernetes.io/version: "1.8.13"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
      app.kubernetes.io/instance: fluent-bit-http
  template:
    metadata:
      annotations:
        checksum/config: d4dede8e827375e829362219e8abf6884ed1fe84fc809e5d3cfcbcd5e88f45b9
        checksum/luascripts: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        app.kubernetes.io/name: fluent-bit
        app.kubernetes.io/instance: fluent-bit-http
    spec:
      serviceAccountName: fluent-bit-http
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: fluent-bit
          image: "coralogixrepo/coralogix-fluent-bit-multiarch:v0.0.1"
          imagePullPolicy: Always
          env:
            - name: APP_NAME_SYSTEMD
              value: systemd
            - name: SUB_SYSTEM_SYSTEMD
              value: _SYSTEMD_UNIT
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: APP_NAME
              value: "Prod"
            - name: SUB_SYSTEM
              value: "kubernetes.container_name"
            - name: ENDPOINT
              value: "api.eu2.coralogix.com"
          envFrom:
            - secretRef:
                name: integrations-privatekey
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 250Mi
          volumeMounts:
            - mountPath: /fluent-bit/etc/fluent-bit.conf
              name: config
              subPath: fluent-bit.conf
            - mountPath: /fluent-bit/etc/custom_parsers.conf
              name: config
              subPath: custom_parsers.conf
            - name: config
              mountPath: /fluent-bit/etc/filters-systemd.conf
              subPath: filters-systemd.conf
            - name: config
              mountPath: /fluent-bit/etc/input-systemd.conf
              subPath: input-systemd.conf
            - name: config
              mountPath: /fluent-bit/etc/output-systemd.conf
              subPath: output-systemd.conf
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /etc/machine-id
              name: etcmachineid
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: fluent-bit-http
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
        - hostPath:
            path: /etc/machine-id
            type: File
          name: etcmachineid
      tolerations:
        - operator: Exists
---
# Source: fluent-bit-http/charts/fluent-bit/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "fluent-bit-http-test-connection"
  labels:
    helm.sh/chart: fluent-bit-0.19.20
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit-http
    app.kubernetes.io/version: "1.8.13"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: "busybox:latest"
      imagePullPolicy: Always
      command: ['wget']
      args: ['fluent-bit-http:2020']
  restartPolicy: Never
