apiVersion: v2
name: prometheus-agent-coralogix
namespace: observability
description: Prometheus running in agent mode
version: 0.0.3
appVersion: 0.61.1
keywords:
  - prometheus
  - agent
maintainers:
  - name: support
    email: support@coralogix.com
