prometheus:
  prometheusSpec:
    externalLabels:
      prometheus: coralogix
    remoteWrite:
    - authorization:
        credentials:
          name: coralogix-keys
          key: PRIVATE_KEY
      name: prometheus-agent-coralogix
      queueConfig:
        capacity: 2500
        maxSamplesPerSend: 1000
        maxShards: 200
      remoteTimeout: 120s
      url: https://ingress.coralogix.com/prometheus/v1
    storageSpec:
      volumeClaimTemplate:
        metadata:
          labels:
            prometheus: coralogix
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi
          storageClassName: monitoring
