AWSTemplateFormatVersion: 2010-09-09
Description: The template used to create an Otel ECS Service from on an ECS Console.

Parameters:
  ClusterName:
    Type: String

  Image:
    Description: The opentelemetry image used to start the container.
    Type: String
    Default: coralogixrepo/otel-coralogix-ecs

  Memory:
    Description: |
      The amount of memory (in MiB) used by the task.
      Note that you cluster must have sufficient memory available to support the given value.
    Type: Number
    Default: 256

  CoralogixRegion:
      Type: String
      Description: The Coralogix location region [Europe, Europe2, India, Singapore, US]
      AllowedValues:
        - Europe
        - Europe2
        - India
        - Singapore
        - US

  ApplicationName:
    Type: String
    Description: The name of your application
    MinLength: 1
    MaxLength: 64

  SubsystemName:
    Type: String
    Description: The subsystem name of your application
    MinLength: 1
    MaxLength: 64
    Default: ${AWS::AccountId}

  PrivateKey:
    Type: String
    Description: The Coralogix private key which is used to validate your authenticity
    AllowedPattern: '[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}'
    ConstraintDescription: The PrivateKey should be valid UUID string
    MinLength: 36
    MaxLength: 36
    NoEcho: true


Mappings:
  CoralogixRegionMap:
    Europe:
      Api: https://api.coralogix.com/api/v1/logs
      Metrics: otel-metrics.coralogix.com:443
      Traces: otel-traces.coralogix.com:443
      Logs: otel-logs.coralogix.com:443
    Europe2:
      Api: https://api.eu2.coralogix.com/api/v1/logs
      Metrics: otel-metrics.coralogix.com:443
      Traces: otel-traces.coralogix.com:443
      Logs: otel-logs.coralogix.com:443
    India:
      Api: https://api.app.coralogix.in/api/v1/logs
      Metrics: otel-metrics.coralogix.in:443
      Traces: otel-traces.coralogix.in:443
      Logs: otel-logs.coralogix.in:443
    Singapore:
      Api: https://api.coralogixsg.com/api/v1/logs
      Metrics: otel-metrics.coralogix.com:443
      Traces: otel-traces.coralogix.com:443
      Logs: otel-logs.coralogix.com:443
    US:
      Api: https://api.coralogix.us/api/v1/logs
      Metrics: otel-metrics.coralogix.us:443
      Traces: otel-traces.coralogix.us:443
      Logs: otel-logs.coralogix.us:443


Resources:
  TaskDefinition: 
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions:
        - Name: coralogix-otel-agent
          Cpu: 0
          Memory: !Ref Memory
          Image: !Ref Image
          Essential: true

          PortMappings:
            - HostPort: 0
              Protocol: tcp
              ContainerPort: 4317
            
            - HostPort: 0
              Protocol: tcp
              ContainerPort: 4318
          
          Environment:
            - Name: OTEL_RESOURCE_ATTRIBUTES
              Value: !Sub APP_NAME=${ApplicationName},SUB_SYS=${SubsystemName}
           
            - Name: PRIVATE_KEY
              Value: !Ref PrivateKey
           
            - Name: TRACES_ENDPOINT
              Value: !FindInMap [CoralogixRegionMap, !Ref CoralogixRegion, Traces]
           
            - Name: METRICS_ENDPOINT
              Value: !FindInMap [CoralogixRegionMap, !Ref CoralogixRegion, Metrics]

            - Name: LOGS_ENDPOINT
              Value: !FindInMap [CoralogixRegionMap, !Ref CoralogixRegion, Api]

          MountPoints:
            - SourceVolume: hostfs
              ContainerPath: "/hostfs"
              ReadOnly: True

      Family: opentelemetry
      RequiresCompatibilities:
        - EC2
      NetworkMode: bridge
      Volumes:
        - Name: hostfs
          Host:
            SourcePath: "/"
        
  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref ClusterName
      TaskDefinition: !GetAtt TaskDefinition.TaskDefinitionArn
      LaunchType: EC2
      ServiceName: coralogix-otel-agent
      SchedulingStrategy: DAEMON
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false
      PlacementStrategies: []
      PlacementConstraints: []
      Tags:
        - Key: 'ecs:service:stackId'
          Value: !Ref 'AWS::StackId'
      EnableECSManagedTags: true


