receivers:
  filelog:
    start_at: end
    include:
      - /hostfs/var/log/*.log
      - /hostfs/var/log/messages
      - /hostfs/var/log/dmesg
      - /hostfs/var/log/xm/*.log
      - /hostfs/var/lib/docker/containers/*/*.log
    include_file_path: true

exporters:
  logging:
  coralogix:
    logs:
      endpoint: "$LOGS_ENDPOINT"
    private_key: "$PRIVATE_KEY"
    application_name: "OTel"
    subsystem_name: "ECS"
    application_name_attributes:
    - "APP_NAME"
    - "service.namespace"
    subsystem_name_attributes:
    - "SUB_SYS"
    - "aws.ecs.task.family"
    - "service.name"
    timeout: 30s

service:
  pipelines:
    logs:
      receivers: 
        - filelog
      exporters:
        - logging
        - coralogix