
name: FluentBit-Coralogix-Chart

on:
  push:
    branches: master
    paths: 
      - 'logs/fluent-bit/k8s-helm/coralogix/Chart.yaml'
      - 'logs/fluent-bit/k8s-helm/coralogix/values.yaml'

env:
  CHART_VERSION: $(yq eval '.version' logs/fluent-bit/k8s-helm/coralogix/Chart.yaml)
  CHART_NAME: fluent-bit-coralogix
  ARTIFACTORY_URL: https://cgx.jfrog.io/artifactory/
  ARTIFACTORY_USERNAME: integrations-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Setup Helm Repo
        run: |
          helm repo add coralogix-charts-virtual ${{ env.ARTIFACTORY_URL }}coralogix-charts-virtual --username ${{ env.ARTIFACTORY_USERNAME }} --password ${{ secrets.ARTIFACTORY_NONUSER_ACCESS_TOKEN }}
          helm repo update
          helm dependency build ./logs/fluent-bit/k8s-helm/coralogix/
          cd logs/fluent-bit/k8s-helm/coralogix
          helm package .
      -
        name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2.1.0
        with:
          version: 2.12.1
      -
        name: use-jfrog-cli
        run: |
          cd logs/fluent-bit/k8s-helm/coralogix
          jfrog rt upload --access-token ${{ secrets.ARTIFACTORY_NONUSER_ACCESS_TOKEN }} "${{ env.CHART_NAME }}-*.tgz" coralogix-charts --url ${{ env.ARTIFACTORY_URL }}
